[phases.setup]
nixPkgs = ["nodejs", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
    "npm install",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "gunicorn wsgi --chdir ./src/ --bind 0.0.0.0:$PORT"

[variables]
FLASK_APP = "src/app.py"
FLASK_ENV = "production"
