[phases.setup]
nixPkgs = ["nodejs_20", "python311"]

[phases.install]
cmds = [
    "chmod +x railway_build_test.sh",
    "./railway_build_test.sh"
]

[start]
cmd = "python test_app.py"

[variables]
NODE_ENV = "production"
PYTHONUNBUFFERED = "1"
