[phases.setup]
nixPkgs = ["nodejs_20", "python311", "postgresql"]

[phases.install]
cmds = [
    "chmod +x railway_build.sh",
    "./railway_build.sh"
]

[phases.build]
cmds = [
    "echo 'Build phase completada'"
]

[start]
cmd = "python railway_app.py"

[variables]
NODE_ENV = "production"
PYTHONUNBUFFERED = "1"
