[phases.setup]
nixPkgs = ["nodejs", "python311"]

[phases.install]
cmds = [
  "pip install flask",
  "npm install"
]

[phases.build]
cmds = [
  "cp env.production .env",
  "export NODE_ENV=production",
  "npm run build"
]

[start]
cmd = "python test_app.py"
