[build]
builder = "nixpacks"

[deploy]
startCommand = "python python_backend/simple_server.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11.7" 