[build]
builder = "nixpacks"
buildCommand = "chmod +x railway_build.sh && ./railway_build.sh"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python railway_app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300

[deploy.healthcheck]
path = "/health"
timeout = 300
